---
language: eng

DataProvider: sqlite

MySQLSettings:
  Host: 127.0.0.1
  Port: 3306
  Username: default
  Password: password
  DatabaseName: MyPlot
  ShutdownOnFailure: false

UseEconomy: false

PlotCacheSize: 256

ShowPlotPopup: true

ClearBlocksPerTick: 256

DefaultWorld:

  RestrictEntityMovement: true

  RestrictPVP: false

  UpdatePlotLiquids: false
  
  ClaimPrice: 0
  ClearPrice: 0
  DisposePrice: 0
  ResetPrice: 0

  PlotSize: 32
  GroundHeight: 64
  RoadWidth: 9

  RoadBlock: '5:1'
  WallBlock: '44:0'
  PlotFloorBlock: '2:0'
  PlotFillBlock: '3:0'
  BottomBlock: '7:0'
...
